# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Test driver for Bash script tests

import("//build/go/go_binary.gni")

go_binary("host_runner") {
  visibility = [
    "//tools/devshell/*",
    "//vendor/*",
  ]
  sources = [ "main.go" ]
}
