# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")

package(default_applicable_licenses = ["//:license"])

fidl_library(
    name = "fuchsia.pkg.test",
    testonly = True,
    srcs = [
        "realm_factory.test.fidl",
    ],
    api_area = "Software Delivery",
    category = "compat_test",
    stable = True,
    visibility = [
        "//sdk/fidl:__pkg__",
        "//src/sys/pkg/tests/pkgdir:__subpackages__",
    ],
    deps = [
        "//sdk/fidl/fuchsia.component.sandbox",
        "//sdk/fidl/fuchsia.io",
        "//sdk/fidl/fuchsia.testing.harness",
        "//zircon/vdso/zx",
    ],
)
