# Copyright 2024 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/stall.h" ]
}

kernel_rust_mod("stall_rs") {
  output_name = "stall"
  source_root = "src/mod.rs"
  sources = [ "src/mod.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
    "//src/lib/ksync",
    "//src/lib/lazy_init:lazy_init_rs",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/init:init_rust",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("stall") {
  public_deps = [ ":headers" ]

  sources = [ "stall.cc" ]
  deps = [ ":stall_rs" ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
