# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fuchsia-component",
    srcs = ["src/lib.rs"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/lib/fuchsia-component/client",
        "//src/lib/fuchsia-component/directory",
        "//src/lib/fuchsia-component/escrow",
        "//src/lib/fuchsia-component/runtime",
        "//src/lib/fuchsia-component/server",
    ],
)
