# Copyright 2025 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "pdev/clocks_and_pmic.h" ]
}

kernel_rust_mod("clocks_and_pmic-rs") {
  output_name = "pdev_clocks_and_pmic"
  source_root = "clocks_and_pmic.rs"
  sources = [ "clocks_and_pmic.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/zr",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("clocks_and_pmic") {
  sources = [ "clocks_and_pmic_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [ ":clocks_and_pmic-rs" ]
}
