# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "shell-process",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    visibility = [
        "//src/sys/pkg/tests/far:__pkg__",
        "//src/sys/pkg/tests/pkgctl:__pkg__",
        "//src/sys/pkg/tests/update:__pkg__",
    ],
    deps = [
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//sdk/rust/zx",
        "//src/lib/fdio/rust:fdio",
        "//src/lib/fidl/rust/fidl",
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-fs",
        "//src/lib/fuchsia-runtime",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:libc",
    ],
)
