# Copyright 2023 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "pdev/timer.h" ]
}

kernel_rust_mod("timer-rs") {
  output_name = "pdev_timer"
  source_root = "timer.rs"
  sources = [ "timer.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
    "//src/lib/zr",
  ]
}

source_set("timer") {
  sources = [ "timer_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [ ":timer-rs" ]
}
