# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

package(default_applicable_licenses = ["//:license"])

# Bluetooth device tests defined in Bazel. These are exported to `fx test` and
# infra builders through //src/connectivity:target_tests.
test_suite(
    name = "target_tests",
    target_compatible_with = ["@platforms//os:fuchsia"],
    tests = [
        "//src/connectivity/bluetooth/lib/bt-obex/objects:bt-obex-objects-tests",
        "//src/connectivity/bluetooth/lib/fuchsia-bluetooth:bluetooth-crate-tests",
        "//src/connectivity/bluetooth/lib/packet-encoding:packet-encoding-tests",
        "//src/connectivity/bluetooth/lib/vigil:vigil-tests",
    ],
    visibility = ["//src/connectivity:__pkg__"],
)
