# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//build/bazel/rules/cc:fx_cc_binary.bzl", "fx_cc_binary")
load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load("//build/bazel/rules/packages:fx_package.bzl", "fx_package")
load(
    "//build/bazel/rules/packages:fx_packaged_binary.bzl",
    "fx_packaged_binary",
)
load("//build/bazel/rules/testing:fx_test.bzl", "fx_test")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "predicates",
    srcs = [
        "status.cc",
    ],
    hdrs = [
        "status.h",
    ],
    target_compatible_with = ["@platforms//os:fuchsia"],
    visibility = [
        "//src/devices:__subpackages__",
        "//src/media:__subpackages__",
        "//vendor/google:__subpackages__",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@fuchsia_sdk//pkg/zx",
    ],
)

# TODO(b/564574581): Replace the targets below with `fx_unittest_package()`
# once https://fuchsia-review.googlesource.com/c/fuchsia/+/1864237 lands, so
# the manifest and packaging boilerplate goes away.
fx_cc_binary(
    name = "predicates-lib-unittests",
    testonly = True,
    srcs = ["predicates_test.cc"],
    tags = ["manual"],
    deps = [":predicates"],
)

fx_packaged_binary(
    name = "predicates-lib-unittests_packaged_bin",
    testonly = True,
    binary = ":predicates-lib-unittests",
    binary_name = "predicates-lib-unittests",
)

fx_component_manifest(
    name = "predicates-lib-test-manifest",
    testonly = True,
    component_name = "predicates-lib-test",
    includes = [
        "//sdk/lib/syslog:client.shard.cml",
        "//sdk/lib/syslog:offer.shard.cml",
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/gtest:default.shard.cml",
    ],
    manifest = "meta/predicates_lib_test.cml",
)

fx_test_component(
    name = "predicates-lib-test-component",
    compiled_manifest = ":predicates-lib-test-manifest",
    component_name = "predicates-lib-test",
    deps = [":predicates-lib-unittests_packaged_bin"],
)

fx_package(
    name = "predicates-lib-test-package",
    package_name = "predicates-lib-test",
    test_components = [":predicates-lib-test-component"],
)

fx_test(
    name = "predicates-lib-test",
    environments = ["//build/testing/environments:emu_env"],
    package = ":predicates-lib-test-package",
)
