# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_test_suite.gni")

source_set("predicates") {
  testonly = true
  sources = [
    "status.cc",
    "status.h",
  ]
  public_deps = [
    # "status.h" has #include <gtest/gtest.h>.
    "//third_party/googletest:gtest",

    # "status.h" has #include <zircon/status.h>.
    "//src/zircon/lib/zircon:headers",

    # "status.h" has #include <lib/fit/result.h>
    "//sdk/lib/fit",
  ]
}

if (is_fuchsia) {
  bazel_test_suite("predicates-lib-test") {
    target_tests = [ "//src/lib/testing/predicates:predicates-lib-test" ]
  }

  group("tests") {
    testonly = true
    deps = [ ":predicates-lib-test" ]
  }
}
