# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_binary", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "server",
    srcs = ["src/server.rs"],
    crate_root = "src/server.rs",
    edition = "2024",
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.starnix.container:fuchsia.starnix.container_rust",
        "//sdk/fidl/fuchsia.vsock:fuchsia.vsock_rust",
        "//sdk/rust/zx",
        "//src/lib/fidl/rust/fidl",
        "//src/lib/fuchsia-component",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:log",
    ],
)

rustc_binary(
    name = "bin",
    srcs = ["src/main.rs"],
    crate_name = "adb_proxy",
    edition = "2024",
    deps = [
        ":server",
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:anyhow",
    ],
)
