# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rustc_library.gni")

group("rust") {
  testonly = true  # While using experimental-protocol boot option.
  public_deps = [ ":userboot" ]
}

rustc_library("userboot") {
  testonly = true  # While using experimental-protocol boot option.
  edition = "2024"
  sources = [ "src/lib.rs" ]
  public_deps = [ ".." ]  # Public to propagate static linking configs.
  deps = [
    "//sdk/lib/c/rust",
    "//sdk/rust/zx",
  ]
}
