# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "lib",
    srcs = ["src/lib.rs"],
    crate_name = "input_device_constants",
    edition = "2024",
    # Rust std needs fdio on Fuchsia. GN adds it to every Fuchsia executable,
    # Bazel does not (https://fxbug.dev/42065890), so list it for the test.
    test_deps = ["//sdk/lib/fdio"],
    visibility = [
        "//src/lib/assembly/config_schema:__pkg__",
        "//src/ui/lib/input_pipeline:__pkg__",
    ],
    with_unit_tests = True,
    deps = [
        "//third_party/rust_crates/vendor:log",
        "//third_party/rust_crates/vendor:schemars",
        "//third_party/rust_crates/vendor:serde",
    ],
)
