# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load("//build/bazel/rules/packages:fx_package.bzl", "fx_package")
load("//build/bazel/rules/packages:fx_packaged_binary.bzl", "fx_packaged_binary")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")
load("//build/bazel/rules/testing:fx_test.bzl", "fx_test")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "seq_lock",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//src/starnix/build:kernel_library_config",
    visibility = [
        "//src/starnix/kernel/core:__pkg__",
        "//src/starnix/modules/selinuxfs:__pkg__",
    ],
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/fuchsia-runtime",
        "//src/starnix/lib/starnix_logging",
        "//third_party/rust_crates/vendor:zerocopy",
    ],
)

# @bazel2gn:skip
fx_packaged_binary(
    name = "seq_lock_test_packaged_bin",
    testonly = True,
    binary = ":seq_lock_test",
    binary_name = "seq_lock_lib_test",
)

# @bazel2gn:skip
fx_component_manifest(
    name = "seq_lock_tests-manifest",
    testonly = True,
    component_name = "seq_lock_tests",
    includes = [
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/rust:default.shard.cml",
    ],
    manifest = "meta/seq_lock_tests.cml",
)

# @bazel2gn:skip
fx_test_component(
    name = "seq_lock_tests-component",
    compiled_manifest = ":seq_lock_tests-manifest",
    component_name = "seq_lock_tests",
    deps = [":seq_lock_test_packaged_bin"],
)

# @bazel2gn:skip
fx_package(
    name = "seq_lock_tests-package",
    package_name = "seq_lock_tests",
    test_components = [":seq_lock_tests-component"],
)

# @bazel2gn:skip
fx_test(
    name = "seq_lock_tests",
    package = ":seq_lock_tests-package",
)
