# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "kgsl_strings",
    srcs = [
        "lib.rs",  # @bazel2gn:path_overwrite:$target_gen_dir/lib.rs
        ":kgsl_strings.rs",  # @bazel2gn:path_overwrite:$target_gen_dir/kgsl_strings.rs
    ],
    crate_root = "lib.rs",  # @bazel2gn:raw_overwrite:"$target_gen_dir/lib.rs"
    data = [
        ":gen_strings",
    ],  # @bazel2gn:raw_overwrite:[ ":copy_lib", ":gen_strings" ]
    edition = "2024",
    deps = [
        "//src/starnix/lib/starnix_uapi",
    ],
)

genrule(
    name = "gen_strings",
    srcs = ["//src/starnix/lib/linux_uapi:src/arm64.rs"],
    outs = [
        "kgsl_strings.rs",  # @bazel2gn:path_overwrite:$target_gen_dir/kgsl_strings.rs
    ],
    cmd = "python3 $(location :kgsl_strings.rs.py) $< $@",  # @bazel2gn:raw_overwrite:0 not_needed(["cmd"]) script = "kgsl_strings.rs.py" args = [ rebase_path("//src/starnix/lib/linux_uapi/src/arm64.rs", root_build_dir), rebase_path("$target_gen_dir/kgsl_strings.rs", root_build_dir) ]
    tools = [":kgsl_strings.rs.py"],
)
