# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load(
    "//build/bazel/rules/packages:fx_package.bzl",
    "fx_package",
)
load(
    "//build/bazel/rules/packages:fx_packaged_binary.bzl",
    "fx_packaged_binary",
)
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")
load(
    "//build/bazel/rules/testing:fx_test.bzl",
    "fx_test",
)

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "crash_throttling",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//src/starnix/build:kernel_library_config",
    visibility = ["//src/starnix/kernel/core:__pkg__"],
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/diagnostics/inspect/rust:fuchsia-inspect",  # @bazel2gn:path_overwrite://src/lib/diagnostics/inspect/rust
        "//src/starnix/lib/starnix_logging",
        "//src/starnix/lib/starnix_sync",
        "//third_party/rust_crates/vendor:futures",
    ],
)

# @bazel2gn:skip
fx_packaged_binary(
    name = "crash_throttling_test_packaged_bin",
    testonly = True,
    binary = ":crash_throttling_test",
    binary_name = "crash_throttling_lib_test",
)

# @bazel2gn:skip
fx_component_manifest(
    name = "crash-throttling-tests-manifest",
    testonly = True,
    component_name = "crash-throttling-tests",
    includes = [
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/rust:default.shard.cml",
    ],
    manifest = "meta/crash_throttling_tests.cml",
)

# @bazel2gn:skip
fx_test_component(
    name = "crash-throttling-tests-component",
    compiled_manifest = ":crash-throttling-tests-manifest",
    component_name = "crash-throttling-tests",
    deps = [":crash_throttling_test_packaged_bin"],
)

# @bazel2gn:skip
fx_package(
    name = "crash-throttling-tests-package",
    package_name = "crash-throttling-tests",
    test_components = [":crash-throttling-tests-component"],
)

# @bazel2gn:skip
fx_test(
    name = "crash-throttling-tests",
    package = ":crash-throttling-tests-package",
)
