# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/cc:fx_cc_library.bzl", "fx_cc_library")

package(default_applicable_licenses = ["//:license"])

fx_cc_library(
    name = "io-buffer",
    srcs = ["phys-iter.c"],
    hdrs = ["include/lib/io-buffer/phys-iter.h"],
    includes = ["include"],
    public_configs = [":include"],
    visibility = [
        "//src/devices/block/drivers/ahci:__pkg__",
        "//src/devices/lib/io-buffer/tests:__pkg__",
        "//src/devices/usb/lib/usb:__subpackages__",
        "//src/devices/usb/lib/usb-endpoint:__pkg__",
    ],
)
