# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "config",
    srcs = ["src/lib.rs"],
    crate_name = "fshost_assembly_config",
    edition = "2024",
    visibility = [
        "//src/lib/assembly/images_config:__pkg__",
        "//src/storage/fshost:__subpackages__",
    ],
    deps = ["//third_party/rust_crates/vendor:serde"],
)
