# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "sse",
    srcs = [
        "client.go",
        "event.go",
        "sse.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/src/sys/pkg/lib/sse",
    target_compatible_with = HOST_OS_CONSTRAINTS,
)

go_test(
    name = "sse_test",
    srcs = [
        "client_test.go",
        "event_test.go",
        "sse_test.go",
    ],
    embed = [":sse"],
    target_compatible_with = HOST_OS_CONSTRAINTS,
)
