// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#![recursion_limit = "1024"]

use criterion::Criterion;
use criterion::measurement::WallTime;
use fuchsia_criterion::FuchsiaCriterion;
use security::PermissionFlags;
use selinux::policy::AccessVector;
use selinux::{
    AccessQueryArgs, ConcurrentAccessCache, KernelAccessDecision, KernelClass, PerThreadCache,
    SecurityId, SecurityServer,
};
use starnix_core::security;
use starnix_core::task::CurrentTask;
use starnix_core::testing::{PanickingFile, spawn_kernel_with_selinux_and_run};
use std::hint::black_box;
use std::num::NonZeroU32;
use std::sync::Arc;
use std::time::Duration;

const POLICY_BYTES: &[u8] =
    include_bytes!("../../../../lib/selinux/testdata/policies/aosp_sepolicy");

/// Number of dynamic SIDs minted in [`populate_sid_table`] to give the `SidTable` a realistic
/// size prior to running benchmarks.
const POPULATED_SID_TABLE_SIZE: u32 = 1024;

/// Returns `base_context` with four MCS categories appended by mapping the four octets of `id`
/// (from lowest- to highest-order) into `c0..c255`, `c256..c511`, `c512..c767`, and `c768..c1023`.
///
/// `base_context` must have a single sensitivity and no categories, e.g. `"u:r:kernel:s0"`.
fn context_with_category_id(base_context: &str, id: u32) -> String {
    let [b0, b1, b2, b3] = id.to_le_bytes();
    format!(
        "{base_context}:c{},c{},c{},c{}",
        u16::from(b0),
        256 + u16::from(b1),
        512 + u16::from(b2),
        768 + u16::from(b3),
    )
}

/// Pre-populates `server`'s `SidTable` with [`POPULATED_SID_TABLE_SIZE`] dynamic SIDs generated by
/// encoding unique 32-bit values into four MCS categories (`c0..c1023`).
fn populate_sid_table(server: &SecurityServer) {
    for id in 0..POPULATED_SID_TABLE_SIZE {
        let context = context_with_category_id("u:r:kernel:s0", id);
        let _ = server.security_context_to_sid(context.as_bytes().into()).unwrap();
    }
}

/// Creates a [`SecurityServer`] with `aosp_sepolicy` loaded and [`populate_sid_table`] applied.
fn new_populated_security_server() -> Arc<SecurityServer> {
    let server = SecurityServer::new_default();
    let _ = server.load_policy(POLICY_BYTES.to_vec()).unwrap();
    populate_sid_table(&server);
    server
}

async fn spawn_test_kernel<F>(callback: F)
where
    F: AsyncFnOnce(&mut CurrentTask) + Send + Sync + 'static,
{
    spawn_kernel_with_selinux_and_run(async |current_task, security_server| {
        security_server.load_policy(POLICY_BYTES.to_vec()).unwrap();
        populate_sid_table(security_server);
        callback(current_task).await
    })
    .await;
}

fn create_file_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    name: &'static str,
    current_task: &'static CurrentTask,
    hook_closure: impl Fn(&CurrentTask, &starnix_core::vfs::FileObject) + Send + Sync + 'static,
) {
    let file = Arc::new(PanickingFile::new_file(current_task));

    let _ = group.bench_function(name, move |bench| {
        let file = file.clone();
        bench.iter(|| {
            hook_closure(current_task, &file);
        })
    });
}

fn load_policy_bench(group: &mut criterion::BenchmarkGroup<'_, WallTime>) {
    let _ = group.bench_function("load_policy", move |bench| {
        bench.iter(|| {
            let server = SecurityServer::new_default();
            let _ = black_box(server.load_policy(POLICY_BYTES.to_vec()));
        })
    });
}

fn security_context_to_sid_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    name_suffix: &'static str,
    context_bytes: &'static [u8],
) {
    let server = new_populated_security_server();
    let _ = server.security_context_to_sid(context_bytes.into()).unwrap();

    let _ = group.bench_function(format!("security_context_to_sid_{name_suffix}"), move |bench| {
        bench.iter(|| {
            let _ = black_box(server.security_context_to_sid(context_bytes.into()).unwrap());
        })
    });
}

fn sid_to_security_context_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    name_suffix: &'static str,
    context_bytes: &'static [u8],
) {
    let server = new_populated_security_server();
    let sid = server.security_context_to_sid(context_bytes.into()).unwrap();

    let _ = group.bench_function(format!("sid_to_security_context_{name_suffix}"), move |bench| {
        bench.iter(|| {
            let _ = black_box(server.sid_to_security_context(sid).unwrap());
        })
    });
}

fn compute_access_decision_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    name_suffix: &'static str,
    source_context: &'static [u8],
    target_context: &'static [u8],
) {
    let server = new_populated_security_server();
    let source_sid = server.security_context_to_sid(source_context.into()).unwrap();
    let target_sid = server.security_context_to_sid(target_context.into()).unwrap();
    let class_id = server.class_id_by_name("file").unwrap();
    assert_ne!(source_sid, target_sid, "source and target contexts must resolve to distinct SIDs");
    assert_ne!(
        server.compute_access_decision_raw(source_sid, target_sid, class_id).allow,
        AccessVector::NONE,
        "source and target must match an allow rule"
    );

    let _ = group.bench_function(format!("compute_access_decision_{name_suffix}"), move |bench| {
        bench.iter(|| {
            let _ = black_box(server.compute_access_decision_raw(source_sid, target_sid, class_id));
        })
    });
}

fn compute_create_sid_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    name_suffix: &'static str,
    source_context: &'static [u8],
    target_context: &'static [u8],
) {
    let server = new_populated_security_server();
    let source_sid = server.security_context_to_sid(source_context.into()).unwrap();
    let target_sid = server.security_context_to_sid(target_context.into()).unwrap();
    let class_id = server.class_id_by_name("process").unwrap();
    let created_sid =
        server.compute_create_sid_raw(source_sid, target_sid, class_id, /* name = */ &[]).unwrap();
    assert_ne!(created_sid, source_sid, "source and target must match a `type_transition` rule");
    assert_ne!(created_sid, target_sid, "new process must not inherit the target's label");

    let _ = group.bench_function(format!("compute_create_sid_{name_suffix}"), move |bench| {
        bench.iter(|| {
            let _ = black_box(
                server
                    .compute_create_sid_raw(source_sid, target_sid, class_id, /* name = */ &[])
                    .unwrap(),
            );
        })
    });
}

fn cached_create_sid_filename_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    bench_name: &'static str,
    source_context: &'static [u8],
    target_context: &'static [u8],
    target_class: KernelClass,
    filename: &'static [u8],
) {
    let server = new_populated_security_server();
    let source_sid = server.security_context_to_sid(source_context.into()).unwrap();
    let target_sid = server.security_context_to_sid(target_context.into()).unwrap();
    let local_cache = PerThreadCache::default();
    let permission_check = server.as_permission_check(&local_cache);
    let nameless_sid = permission_check
        .compute_create_sid(source_sid, target_sid, target_class, /* name = */ &[])
        .unwrap();
    let created_sid = permission_check
        .compute_create_sid(source_sid, target_sid, target_class, filename)
        .unwrap();
    if bench_name == "match" {
        assert_ne!(created_sid, nameless_sid, "`match` must hit a filename transition rule");
    } else {
        assert_eq!(
            created_sid, nameless_sid,
            "`{bench_name}` must not hit a filename transition rule"
        );
    }

    let _ =
        group.bench_function(format!("cached_create_sid_filename_{bench_name}"), move |bench| {
            let permission_check = server.as_permission_check(&local_cache);
            bench.iter(|| {
                let _ = black_box(
                    permission_check
                        .compute_create_sid(source_sid, target_sid, target_class, filename)
                        .unwrap(),
                );
            })
        });
}

fn compute_create_sid_filename_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    bench_name: &'static str,
    source_context: &'static [u8],
    target_context: &'static [u8],
    target_class: KernelClass,
    filename: &'static [u8],
) {
    let server = new_populated_security_server();
    let source_sid = server.security_context_to_sid(source_context.into()).unwrap();
    let target_sid = server.security_context_to_sid(target_context.into()).unwrap();
    let class_id = server.class_id_by_name(target_class.name()).unwrap();
    let nameless_sid =
        server.compute_create_sid_raw(source_sid, target_sid, class_id, /* name = */ &[]).unwrap();
    let created_sid =
        server.compute_create_sid_raw(source_sid, target_sid, class_id, filename).unwrap();
    if bench_name == "match" {
        assert_ne!(created_sid, nameless_sid, "`match` must hit a filename transition rule");
    } else {
        assert_eq!(
            created_sid, nameless_sid,
            "`{bench_name}` must not hit a filename transition rule"
        );
    }

    let _ =
        group.bench_function(format!("compute_create_sid_filename_{bench_name}"), move |bench| {
            bench.iter(|| {
                let _ = black_box(
                    server
                        .compute_create_sid_raw(source_sid, target_sid, class_id, filename)
                        .unwrap(),
                );
            })
        });
}

fn concurrent_access_cache_get_bench(group: &mut criterion::BenchmarkGroup<'_, WallTime>) {
    let cache = ConcurrentAccessCache::new(selinux::DEFAULT_SHARED_SIZE.access_cache_capacity);
    let value = KernelAccessDecision {
        allow: AccessVector::ALL,
        audit: AccessVector::NONE,
        flags: 0,
        todo_bug: None,
    };

    let keys: Vec<_> = (1..=1000)
        .map(|index| AccessQueryArgs {
            source_sid: SecurityId(NonZeroU32::new(index).unwrap()),
            target_sid: SecurityId(NonZeroU32::new(index + 1).unwrap()),
            target_class: KernelClass::Process,
        })
        .collect();

    for key in &keys {
        let _ = cache.get_or_try_insert::<()>(key, || Ok(value));
    }

    let _ = group.bench_function("concurrent_access_cache_get", move |bench| {
        bench.iter(|| {
            for key in &keys {
                let _ = black_box(cache.get_or_try_insert::<()>(key, || Ok(value)));
            }
        })
    });
}

fn file_permission_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    current_task: &'static CurrentTask,
) {
    create_file_bench(group, "file_permission", current_task, |task, file| {
        let _ = black_box(security::file_permission(task, file, PermissionFlags::READ).unwrap());
    });
}

fn fs_node_permission_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    current_task: &'static CurrentTask,
) {
    create_file_bench(group, "fs_node_permission", current_task, |task, file| {
        let _ = black_box(
            security::fs_node_permission(
                task,
                file.node(),
                PermissionFlags::READ,
                security::Auditable::None,
            )
            .unwrap(),
        );
    });
}

fn check_file_ioctl_access_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    current_task: &'static CurrentTask,
) {
    create_file_bench(group, "check_file_ioctl_access", current_task, |task, file| {
        let _ =
            black_box(security::check_file_ioctl_access(task, file, starnix_uapi::TCGETS).unwrap());
    });
}

fn binder_transaction_bench(
    group: &mut criterion::BenchmarkGroup<'_, WallTime>,
    current_task: &'static CurrentTask,
) {
    let _ = group.bench_function("binder_transaction", move |bench| {
        let creds = current_task.current_creds();
        bench.iter(|| {
            let _ = black_box(security::binder_transaction(current_task, &creds, &creds).unwrap());
        })
    });
}

fn main() {
    let mut executor = fuchsia_async::LocalExecutor::default();
    executor.run_singlethreaded(spawn_test_kernel(async move |current_task| {
        // SAFETY: The Criterion benchmarks run synchronously and block until completion
        // entirely within the scope of this closure. Therefore, `current_task` is guaranteed
        // to outlive the benchmark execution, making it safe to cast to a `'static` reference.
        let current_task = unsafe { &*(current_task as *const CurrentTask) };

        // List of benchmark programs is passed as the argument list from the
        // component manifest. The arguments passed by the test executor are
        // separated from the arguments in the manifest file by adding "--" at
        // the end of the argument list in the manifest file.
        let mut args: Vec<_> = std::env::args().collect();
        let Some(separator_pos) = args.iter().position(|arg| arg == "--") else {
            eprintln!("{:?}\n-- not found in the argument list", args);
            std::process::exit(1);
        };

        // Replace separator with the program name.
        args[separator_pos] = args[0].clone();

        let benchmark_args: Vec<_> = args[separator_pos..].iter().map(|arg| &**arg).collect();

        let mut fuchsia_criterion = FuchsiaCriterion::fuchsia_bench_with_args(&benchmark_args);
        let criterion: &mut Criterion = &mut fuchsia_criterion;

        *criterion = std::mem::take(criterion)
            .warm_up_time(Duration::from_millis(100))
            .measurement_time(Duration::from_secs(1))
            .sample_size(50);

        let mut group = criterion.benchmark_group("fuchsia.sestarnix");
        load_policy_bench(&mut group);
        security_context_to_sid_bench(&mut group, "simple", b"u:r:kernel:s0");
        security_context_to_sid_bench(&mut group, "c0_c255", b"u:r:kernel:s0:c0.c255");
        sid_to_security_context_bench(&mut group, "simple", b"u:r:kernel:s0");
        sid_to_security_context_bench(&mut group, "c0_c255", b"u:r:kernel:s0:c0.c255");
        compute_access_decision_bench(
            &mut group,
            "simple",
            b"u:r:untrusted_app:s0",
            b"u:object_r:app_data_file:s0",
        );
        compute_access_decision_bench(
            &mut group,
            "c0_c255",
            b"u:r:untrusted_app:s0:c0.c255",
            b"u:object_r:app_data_file:s0:c0.c255",
        );
        compute_create_sid_bench(
            &mut group,
            "simple",
            b"u:r:kernel:s0",
            b"u:object_r:init_exec:s0",
        );
        compute_create_sid_bench(
            &mut group,
            "c0_c255",
            b"u:r:kernel:s0:c0.c255",
            b"u:object_r:init_exec:s0:c0.c255",
        );
        // `system_data_file` has filename transition rules (`ndebugsocket` on `sock_file`), while
        // `tmpfs` has no filename transition rules (`no_target_rules`).
        let filename_transition_cases: &[(&str, &[u8], &[u8], KernelClass, &[u8])] = &[
            (
                "match",
                b"u:r:system_server:s0",
                b"u:object_r:system_data_file:s0",
                KernelClass::SockFile,
                b"ndebugsocket",
            ),
            (
                "no_match",
                b"u:r:system_server:s0",
                b"u:object_r:system_data_file:s0",
                KernelClass::SockFile,
                b"unlikely_filename_1234",
            ),
            (
                "no_target_rules",
                b"u:r:init:s0",
                b"u:object_r:tmpfs:s0",
                KernelClass::File,
                b"unlikely_filename_1234",
            ),
            ("nameless", b"u:r:init:s0", b"u:object_r:tmpfs:s0", KernelClass::File, b""),
        ];
        for &(bench_name, source, target, target_class, filename) in filename_transition_cases {
            compute_create_sid_filename_bench(
                &mut group,
                bench_name,
                source,
                target,
                target_class,
                filename,
            );
            cached_create_sid_filename_bench(
                &mut group,
                bench_name,
                source,
                target,
                target_class,
                filename,
            );
        }
        concurrent_access_cache_get_bench(&mut group);
        file_permission_bench(&mut group, current_task);
        fs_node_permission_bench(&mut group, current_task);
        check_file_ioctl_access_bench(&mut group, current_task);
        binder_transaction_bench(&mut group, current_task);
        group.finish();
    }));
}
