# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "proptest-support",
    testonly = True,
    srcs = ["src/lib.rs"],
    build_flags = ["//build/config/rust/lints:deny_unused_results"],
    edition = "2024",
    visibility = [
        "//src/connectivity/network/netlink:__pkg__",
        "//src/connectivity/network/netstack3:__subpackages__",
        "//src/lib/windowed-stats:__pkg__",
    ],
    deps = ["//third_party/rust_crates/vendor:proptest"],
)
