# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fidl_table_validation",
    srcs = ["src/lib.rs"],
    edition = "2024",
    proc_macro_deps = [
        "//src/lib/fidl_table_validation/fidl_table_validation_derive",
    ],
    visibility = [
        "//src/connectivity/bluetooth/lib/fuchsia-bluetooth:__pkg__",
        "//src/connectivity/bluetooth/profiles/bt-a2dp:__pkg__",
        "//src/connectivity/bluetooth/profiles/bt-avrcp-target:__pkg__",
        "//src/connectivity/lib/fidl_fuchsia_net_dhcpv6_ext:__pkg__",
        "//src/connectivity/lib/fidl_fuchsia_net_neighbor_ext:__pkg__",
        "//src/connectivity/lib/network-device/rust:__pkg__",
        "//src/connectivity/network/netstack3:__pkg__",
        "//src/diagnostics/archivist:__subpackages__",
        "//src/lib/fidl_table_validation/fidl_table_validation_tests:__pkg__",
        "//src/lib/network/fidl_fuchsia_net_interfaces_ext:__pkg__",
        "//src/media/sessions:__pkg__",
        "//src/media/stream_processors/fuchsia-stream-processors:__pkg__",
        "//src/media/stream_processors/test:__pkg__",
    ],
    deps = [
        "//third_party/rust_crates/vendor:anyhow",
    ],
)
