# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "test-harness",
    srcs = ["src/lib.rs"],
    edition = "2024",
    proc_macro_deps = [
        "//src/connectivity/bluetooth/testing/test-harness-macro",
    ],
    rustc_flags = ["-Dunused_results"],
    visibility = ["//src/connectivity/bluetooth:__subpackages__"],
    deps = [
        "//src/lib/diagnostics/log/rust",
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
    ],
)
