# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/toolchain/toolchain_environment.gni")
import("//build/zircon/c_utils.gni")
import("//zircon/kernel/kernel_rust_mod.gni")
import("//zircon/kernel/params.gni")
import("//zircon/kernel/phys/kernel_elf_binary.gni")

_kernel_executable_deps = [
  "//zircon/kernel/phys:physboot.kernel",
  "//zircon/kernel/top",
]

_kernel_executable_cpu_deps = {
  arm64 = [ "//zircon/kernel/platform/generic-arm" ]
  riscv64 = [ "//zircon/kernel/platform/generic-riscv64" ]
  x64 = [ "//zircon/kernel/platform/pc" ]
}

# Represents a kernel executable (i.e., a kernel in ELF form) evaluated under
# the current switchset.
#
# Subtargets
#
#   * $target_name.rsp
#     The link_output_rspfile() containing the output name of the kernel
#     executable.
#
# Parameters
#
#   * deps
#    - Optional: Additional sources to link into the kernel.
#    - Type: list(label)
#    - Default: []
#
#   * data_deps
#    - Optional: Can be used to bring extra files into the kernel package or
#      extra ZBI items into the image.
#    - Type: list(label)
#    - Default: []
#
#   * testonly, visibility
#     - Optional: Standard GN meanings.
#
template("kernel_executable") {
  assert(toolchain_environment == "kernel",
         "kernel_executable() can only be used in the kernel environment")

  main_target = target_name
  validate_symbols_target = "_kernel_executable.$target_name.validate"
  rust_mod_target = "_kernel_executable.$target_name.rust_mod"
  rsp_target = "$target_name.rsp"

  _kernel_deps =
      _kernel_executable_deps + _kernel_executable_cpu_deps[current_cpu]
  if (defined(invoker.deps)) {
    _kernel_deps += invoker.deps
  }

  # GN's support for Rust targets only handles other Rust crates (ultimately,
  # rust_library() or rust_proc_macro() targets) in "direct" deps.  That is,
  # either literal `deps` list in target itself, or their equivalent via
  # `public_deps` propagation.  These get tool() substitutions in {{externs}}
  # of `--extern name=...` switches for each of those; the Rust compiler in
  # turn makes those available for `name::` use, and indeed warns if there is
  # none.  Those, and all transitive Rust crate deps---only via "direct" deps
  # at each Rust crate target, get tool() substitutions in {{rustdeps}} of
  # `-Ldependency=...` switches so that the Rust compiler can find all the
  # dependencies of those `--extern` crates.
  #
  # The kernel executable() has no Rust crates as direct deps.  Everything
  # comes only via indirect deps on group() and source_set() targets.  So GN
  # puts nothing into {{externs}} or {{rustdeps}}.  The code here must make up
  # some equivalent plumbing for the kernel's dependencies on Rust crates.

  # The kernel_rust_mod() target here rolls up all the Rust source files for
  # the kernel crate itself.  kernel_rust_mod() targets in the deps graph
  # contribute `mod ...;` lines to define Rust modules for the kernel crate.
  # Submodules have already been rolled up by the most-direct kernel_rust_mod()
  # targets; the ones collected here are the top-level modules of the crate.
  #
  # kernel_rust_crate() targets instead contribute up `use ... as _;` lines
  # here to tell Rust to link that crate in despite no other apparent reason.
  kernel_rust_mod(rust_mod_target) {
    visibility = [ ":*" ]
    forward_variables_from(invoker, [ "testonly" ])

    # This will roll up all the "top-level" kernel_rust_mod() targets as
    # submodules of the `_imports` module within the `kernel` crate.  All those
    # top-level modules are reexported as `$crate::<name>`.
    output_name = "kernel_executable_not_used_mod"  # Not really used.
    preamble = [
      "#![no_std]",
      "#![no_main]",
      "#[allow(unused_imports)]",
      "pub(crate) use _imports::*;",
    ]
    sources = []
    deps = _kernel_deps
  }
  _kernel_deps += [ ":$rust_mod_target" ]

  # The .rs file generated by kernel_rust_mod() will be the sole $sources list
  # of the kernel executable() below.  The deps ensure all the non-Rust code
  # goes into the link.  What's not handled is any Rust crates used by the
  # kernel's Rust sources, i.e. rust_library() or rust_proc_macro() targets
  # that appear in the deps graph.  There are a few ways that a Rust crate can
  # be referenced:
  #
  #  1. Kernel Rust sources use `crate_name::...` items in some fashion.
  #     * The defining crate should appear in $deps of the kernel_rust_mod()
  #       that lists the `.rs` source file where it's used.
  #
  #  2. A crate referred to via #1 has another crate in its $deps list.
  #
  #  3. A kernel_rust_crate() target is in the $deps graph.
  #     * This is used when the crate defines `extern "C"` symbols that are
  #       used by non-Rust code.
  #     * The source_set() containing the non-Rust source that refers to such a
  #       symbol should have the kernel_rust_crate() target in its $deps.
  #     * The kernel_rust_mod() target defined above effectively transforms
  #       this into a case of #1 via `use crate_name as _;` in a source file.

  gen_rsp_files = [
    {
      # For #1, --extern switches are needed for each rust_library() or
      # rust_proc_macro() that appears in the transitive deps graph across
      # kernel_rust_mod() and non-Rust targets.
      key = "kernel_rust_externs"

      # This excludes any that are only indirect deps via another Rust crate.
      barrier = [ "rust_barrier" ]
    },
    {
      # For #2, -Ldependency=... switches are needed for each rust_library() or
      # rust_proc_macro() that appears in the whole transitive deps graph.
      key = "rust_aux_searchdir"
      barrier = []
    },
  ]

  foreach(gen, gen_rsp_files) {
    generated_file("$main_target.${gen.key}.rsp") {
      visibility = [ ":*" ]
      forward_variables_from(invoker, [ "testonly" ])
      outputs = [ "$target_gen_dir/$target_name" ]
      output_conversion = "list lines"
      walk_keys = gen.barrier
      data_keys = [ gen.key ]
      deps = _kernel_deps
    }
  }

  kernel_elf_binary(main_target) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "visibility",
                           ])
    if (defined(visibility)) {
      visibility += [ ":*" ]
    }

    install_name = "vmzircon"

    configs += [ "//zircon/kernel/switch:kernel_executable.config" ]
    deps = _kernel_deps

    validations = [ ":$validate_symbols_target" ]

    # GN makes an executable() use Rust if its $sources list any Rust files.
    # The only file listed directly here at all is the $crate_root generated by
    # the kernel_rust_mod() target.
    crate_type = "bin"
    sources = get_target_outputs(":$rust_mod_target")
    crate_root = sources[0]
    rustflags = [ "--edition=2024" ]

    # The binary crate is always called "kernel" in every target.
    crate_name = "kernel"

    # Add in the switches that enable what kernel_rust_mod() generated to work.
    inputs = []
    foreach(gen, gen_rsp_files) {
      gen.target = ":$main_target.${gen.key}.rsp"
      deps += [ gen.target ]
      inputs += get_target_outputs(gen.target)
    }
    foreach(file, inputs) {
      rustflags += [ "@" + rebase_path(file, root_build_dir) ]
    }
    if (rust_rbe_enable) {
      rustflags += [ "--remote-inputs=" +
                     string_join(",", rebase_path(inputs, root_build_dir)) ]
    }

    metadata = {
      # Be sure to ignore what the kernel_rust_mod() target generated.
      rust_mod_barrier = []
    }
  }

  rspfile = "$target_gen_dir/$main_target.rsp"
  link_output_rspfile(rsp_target) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "visibility",
                           ])
    if (defined(visibility)) {
      visibility += [ ":$validate_symbols_target" ]
    }
    deps = [ ":$main_target.binary" ]
    outputs = [ rspfile ]
  }

  toolchain_utils_action(validate_symbols_target) {
    forward_variables_from(invoker, [ "testonly" ])
    visibility = [ ":*" ]
    outputs = [ "$target_gen_dir/$target_name.stamp" ]
    script = "//zircon/kernel/scripts/validate-kernel-symbols.py"
    utils = [ "nm" ]
    deps = [
      ":$main_target.binary",
      ":$rsp_target",
    ]
    sources = [ rspfile ]
    depfile = "$target_gen_dir/$target_name.d"
    args = rebase_path(sources + outputs + [ depfile ], root_build_dir)
  }
}
