# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "cml",
    srcs = [
        "src/error.rs",
        "src/features.rs",
        "src/lib.rs",
        "src/load.rs",
        "src/one_or_many.rs",
        "src/translate.rs",
        "src/types/capability.rs",
        "src/types/capability_id.rs",
        "src/types/child.rs",
        "src/types/collection.rs",
        "src/types/common.rs",
        "src/types/document.rs",
        "src/types/environment.rs",
        "src/types/expose.rs",
        "src/types/mod.rs",
        "src/types/offer.rs",
        "src/types/program.rs",
        "src/types/right.rs",
        "src/types/use.rs",
        "src/validate.rs",
    ],
    edition = "2024",
    proc_macro_deps = [
        "//tools/lib/cml/macro",
    ],
    test_deps = [
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:assert_matches",
        "//third_party/rust_crates/vendor:difference",
        "//third_party/rust_crates/vendor:test-case",
    ],
    visibility = [
        "//src/lib/assembly:__subpackages__",
        "//src/security/lib/scrutiny/frontend:__pkg__",
        "//src/sys/lib/cm_rust/testing:__pkg__",
        "//src/sys/lib/runner:__pkg__",
        "//tools/cmc:__pkg__",
        "//tools/component_manager_config:__pkg__",
        "//tools/testgen:__pkg__",
        "//vendor/google:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
        "//sdk/fidl/fuchsia.data:fuchsia.data_rust",
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//src/lib/directed_graph",
        "//src/lib/fidl/rust/fidl",
        "//src/sys/lib/cm_fidl_validator",
        "//src/sys/lib/cm_rust",
        "//src/sys/lib/cm_types",
        "//third_party/rust_crates/vendor:indexmap",
        "//third_party/rust_crates/vendor:itertools",
        "//third_party/rust_crates/vendor:json5format",
        "//third_party/rust_crates/vendor:maplit",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:serde_json",
        "//third_party/rust_crates/vendor:serde_json5",
        "//third_party/rust_crates/vendor:sha2",
        "//tools/lib/config_value_file",
        "//tools/lib/reference_doc",
    ],
)
