# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/devicetree/devicetree.gni")
import("//build/devicetree/devicetree_visitor.gni")
import("//build/test.gni")

group("tests") {
  deps = [ ":i2c-bus-visitor-test" ]
  testonly = true
}

devicetree_visitor("i2c-bus-visitor") {
  sources = [
    "i2c-bus-visitor.cc",
    "i2c-bus-visitor.h",
  ]
  enable_sdk_source_set = true
  category = "internal"
  deps = [
    "//sdk/lib/driver/devicetree/manager:node",
    "//sdk/lib/driver/devicetree/visitors:common-types",
    "//sdk/lib/driver/devicetree/visitors:registration",
    "//sdk/lib/driver/logging/cpp",
    "//zircon/system/ulib/fbl",
  ]
  public_deps = [
    "//sdk/fidl/fuchsia.hardware.i2c.businfo:fuchsia.hardware.i2c.businfo_cpp",
    "//sdk/lib/driver/devicetree/visitors:driver-visitor",
  ]
  non_sdk_deps = [
    "//src/devices/bind/fuchsia:fuchsia_cpp",
    "//src/lib/ddk",
  ]
}

test("i2c-bus-visitor-test-bin") {
  sources = [ "test/i2c-bus-visitor-test.cc" ]
  deps = [
    ":i2c-bus-visitor.static",
    "//sdk/lib/driver/devicetree/testing:visitor-test-helper",
    "//sdk/lib/driver/devicetree/visitors:registry",
    "//sdk/lib/driver/devicetree/visitors/default/bind-property",
    "//sdk/lib/driver/devicetree/visitors/default/mmio",
    "//src/devices/bind/fuchsia:fuchsia_cpp",
    "//src/devices/bind/fuchsia.platform:fuchsia.platform_cpp",
    "//src/lib/fxl/test:gtest_main",
  ]
}

dtb("i2c-dtb") {
  sources = [ "test/dts/i2c.dts.S" ]

  # -Wno-unique_unit_address is needed because the test DTS (i2c.dts.S)
  # intentionally defines duplicate unit addresses (child@c and child-dup@c)
  # to test duplicate channel detection.
  dtcflags = [ "-Wno-unique_unit_address" ]
}

resource("i2c-dtb-file") {
  sources = get_target_outputs(":i2c-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-dtb" ]
}

dtb("i2c-channels-dtb") {
  sources = [ "test/dts/i2c-channels.dts.S" ]
}

resource("i2c-channels-dtb-file") {
  sources = get_target_outputs(":i2c-channels-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-dtb" ]
}

dtb("i2c-channels-duplicate-names-dtb") {
  sources = [ "test/dts/i2c-channels-duplicate-names.dts.S" ]
}

resource("i2c-channels-duplicate-names-dtb-file") {
  sources = get_target_outputs(":i2c-channels-duplicate-names-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-duplicate-names-dtb" ]
}

dtb("i2c-channels-duplicate-phandles-dtb") {
  sources = [ "test/dts/i2c-channels-duplicate-phandles.dts.S" ]
}

resource("i2c-channels-duplicate-phandles-dtb-file") {
  sources = get_target_outputs(":i2c-channels-duplicate-phandles-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-duplicate-phandles-dtb" ]
}

dtb("i2c-channels-grandchild-dtb") {
  sources = [ "test/dts/i2c-channels-grandchild.dts.S" ]
}

resource("i2c-channels-grandchild-dtb-file") {
  sources = get_target_outputs(":i2c-channels-grandchild-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-grandchild-dtb" ]
}

dtb("i2c-channels-multi-address-dtb") {
  sources = [ "test/dts/i2c-channels-multi-address.dts.S" ]
}

resource("i2c-channels-multi-address-dtb-file") {
  sources = get_target_outputs(":i2c-channels-multi-address-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-multi-address-dtb" ]
}

dtb("i2c-channels-multiple-referrers-dtb") {
  sources = [ "test/dts/i2c-channels-multiple-referrers.dts.S" ]
}

resource("i2c-channels-multiple-referrers-dtb-file") {
  sources = get_target_outputs(":i2c-channels-multiple-referrers-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-multiple-referrers-dtb" ]
}

dtb("i2c-channels-names-mismatch-dtb") {
  sources = [ "test/dts/i2c-channels-names-mismatch.dts.S" ]
}

resource("i2c-channels-names-mismatch-dtb-file") {
  sources = get_target_outputs(":i2c-channels-names-mismatch-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-names-mismatch-dtb" ]
}

dtb("i2c-channels-no-names-dtb") {
  sources = [ "test/dts/i2c-channels-no-names.dts.S" ]
}

resource("i2c-channels-no-names-dtb-file") {
  sources = get_target_outputs(":i2c-channels-no-names-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-no-names-dtb" ]
}

dtb("i2c-channels-not-i2c-child-dtb") {
  sources = [ "test/dts/i2c-channels-not-i2c-child.dts.S" ]
}

resource("i2c-channels-not-i2c-child-dtb-file") {
  sources = get_target_outputs(":i2c-channels-not-i2c-child-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-not-i2c-child-dtb" ]
}

dtb("i2c-channels-own-name-collision-dtb") {
  sources = [ "test/dts/i2c-channels-own-name-collision.dts.S" ]
}

resource("i2c-channels-own-name-collision-dtb-file") {
  sources = get_target_outputs(":i2c-channels-own-name-collision-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-own-name-collision-dtb" ]
}

dtb("i2c-channels-referenced-compatible-dtb") {
  sources = [ "test/dts/i2c-channels-referenced-compatible.dts.S" ]
}

resource("i2c-channels-referenced-compatible-dtb-file") {
  sources = get_target_outputs(":i2c-channels-referenced-compatible-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-referenced-compatible-dtb" ]
}

dtb("i2c-channels-self-reference-dtb") {
  sources = [ "test/dts/i2c-channels-self-reference.dts.S" ]
}

resource("i2c-channels-self-reference-dtb-file") {
  sources = get_target_outputs(":i2c-channels-self-reference-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-self-reference-dtb" ]
}

dtb("i2c-channels-shared-address-dtb") {
  sources = [ "test/dts/i2c-channels-shared-address.dts.S" ]

  # -Wno-unique_unit_address is needed because the test DTS
  # (i2c-channels-shared-address.dts.S) intentionally defines duplicate unit
  # addresses (child@c and child-dup@c) to test the rejection of references to
  # a shared address.
  dtcflags = [ "-Wno-unique_unit_address" ]
}

resource("i2c-channels-shared-address-dtb-file") {
  sources = get_target_outputs(":i2c-channels-shared-address-dtb")
  outputs = [ "test-data/{{source_file_part}}" ]
  deps = [ ":i2c-channels-shared-address-dtb" ]
}

fuchsia_unittest_package("i2c-bus-visitor-test") {
  component_name = "i2c-bus-visitor-test"
  deps = [
    ":i2c-bus-visitor-test-bin",
    ":i2c-channels-dtb-file",
    ":i2c-channels-duplicate-names-dtb-file",
    ":i2c-channels-duplicate-phandles-dtb-file",
    ":i2c-channels-grandchild-dtb-file",
    ":i2c-channels-multi-address-dtb-file",
    ":i2c-channels-multiple-referrers-dtb-file",
    ":i2c-channels-names-mismatch-dtb-file",
    ":i2c-channels-no-names-dtb-file",
    ":i2c-channels-not-i2c-child-dtb-file",
    ":i2c-channels-own-name-collision-dtb-file",
    ":i2c-channels-referenced-compatible-dtb-file",
    ":i2c-channels-self-reference-dtb-file",
    ":i2c-channels-shared-address-dtb-file",
    ":i2c-dtb-file",
  ]

  # The error-case tests log errors.
  test_specs = {
    log_settings = {
      max_severity = "ERROR"
    }
  }
}
