# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "starnix_syscalls",
    srcs = [
        "src/decls.rs",
        "src/lib.rs",
        "src/syscall_arg.rs",
        "src/syscall_result.rs",
    ],
    edition = "2024",
    lint_config = "//src/starnix/build:kernel_library_config",
    proc_macro_deps = [
        "//third_party/rust_crates/vendor:paste",
    ],
    visibility = [
        "//src/starnix/kernel/core:__pkg__",
        "//src/starnix/kernel/syscall_loop:__pkg__",
        "//src/starnix/modules:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//src/starnix/lib/starnix_types",
        "//src/starnix/lib/starnix_uapi",
    ],
)
