// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use lock_ordering_macro::lock_ordering;

lock_ordering! {
    // keep-sorted start
    AioPendingOperationsLock => WaitQueueImplLock,
    AshmemStateLock => FsNodeWriteGuardStateLock,
    AshmemStateLock => MemoryManagerStateLock,
    BeforeFsNodeAppend => FsNodeAppend,
    BinderFreezeLevel => BinderProcessStateLevel,
    BinderFsDevicesLevel => DeviceRegistryStateLevel,
    BinderFsDevicesLevel => FsNodeInfoLevel,
    BinderFsDevicesLevel => MemoryManagerStateLock,
    BinderFsDevicesLevel => RwQueueInnerLock,
    BinderObjectLevel => BinderThreadStateLock,
    BinderProcessSharedMemoryLevel => BinderFreezeLevel,
    BinderProcessSharedMemoryLevel => FsRenameRecursive,
    BinderProcessSharedMemoryLevel => TaskFilesLock,
    BinderProcessStateLevel => BinderContextManagerLevel,
    BinderProcessStateLevel => BinderObjectLevel,
    BinderProcessStateLevel => BinderThreadRequeueEventLock,
    BinderProcsLevel => BinderProcessSharedMemoryLevel,
    BinderThreadStateLock => BinderThreadRequeueEventLock,
    BinderThreadStateLock => MemoryManagerStateLock,
    BinderThreadStateLock => ThreadGroupMutableStateLock,
    BinderThreadStateLock => WaiterEventHandlerLock,
    CgroupChildrenLock => CgroupStateLock,
    CgroupDirectoryInterfaceFilesLock => CgroupChildrenLock,
    CgroupDirectoryInterfaceFilesLock => CgroupDirectoryNodesLock,
    CgroupDirectoryInterfaceFilesLock => RwQueueInnerLock,
    CgroupPidTableLock => CgroupStateLock,
    CgroupStateLock => ThreadGroupMutableStateLock,
    CgroupV1Level => CgroupPidTableLock,
    CrashesPerProcessLock => ThrottledCoreDumpsLock,
    DeviceMapperRegistryDevicesLock => DmDeviceStateLock,
    DeviceMapperRegistryDevicesLock => DynamicThreadSpawnerLock,
    DeviceRegistryStateLevel => NetlinkSocketInnerLock,
    DeviceTerminalsLock => TerminalMutableStateLock,
    DirEntryChildrenLevel => BinderFsDevicesLevel,
    DirEntryChildrenLevel => CgroupDirectoryInterfaceFilesLock,
    DirEntryChildrenLevel => FileSystemEntriesLock,
    DirEntryChildrenLevel => FileSystemPermanentLock,
    DirEntryChildrenLevel => InotifyStateLock,
    DirEntryChildrenLevel => MmDumpable,
    DirEntryChildrenLevel => NetstackDevicesLock,
    DirEntryChildrenLevel => NmfsNetworkManagerLock,
    DirEntryChildrenLevel => SeLinuxPendingEntriesLock,
    DirEntryChildrenLevel => SeLinuxUpdateLock,
    DirEntryChildrenLevel => UnixSocketInnerLock,
    DirEntryChildrenRecursiveLevel => FsNodeInfoRecursiveLevel,
    DirEntryChildrenRecursiveLevel => MemoryDirectoryReaddirPositionLock,
    DmDeviceStateLock => DirEntryChildrenLevel,
    DmDeviceStateLock => MemoryManagerStateLock,
    DynamicFileStateLock => CgroupV1Level,
    DynamicFileStateLock => FsRegistryLock,
    DynamicFileStateLock => MapInfoCacheBufLock,
    DynamicFileStateLock => MemoryManagerStateLock,
    DynamicFileStateLock => MemoryPressureMonitor,
    DynamicFileStateLock => TaskCredsLock,
    EbpfMapStateLevel => EbpfSuspendLock,
    EbpfStateLock => EbpfSuspendLock,
    EbpfStateLock => MemoryManagerStateLock,
    EpollStateLock => BinderProcsLevel,
    EpollStateLock => EventFdInnerLock,
    EpollStateLock => MemoryPressureMonitor,
    EpollStateLock => SuspendResumeManagerInnerLock,
    EpollStateLock => TimerFileInfoLock,
    EpollWaitableStateLock => WaitQueueImplLock,
    ExecutorVmarManagerLock => ThreadGroupPtraceesLock,
    FastrpcInnerState => MemoryManagerStateLock,
    FdTableMutableStateLock => FsNodeInfoLevel,
    FdTableMutableStateLock => MountsLevel,
    FileEpollFilesLock => EpollStateLock,
    FileObjectOffset => BeforeFsNodeAppend,
    FileObjectOffset => DynamicFileStateLock,
    FileObjectOffset => FuseFsNodeInfoLevel,
    FileObjectOffset => FuseNodeStateLock,
    FileObjectOffset => IcmpPingGidsLock,
    FileObjectOffset => OverlayFsDirEntriesLock,
    FileObjectOffset => PerfRingBufferStateLock,
    FileObjectOffset => SeLinuxFsContextSidLock,
    FileObjectOffset => SeLinuxPendingFileSystemsLock,
    FileObjectOffset => SeLinuxQueryCacheResetLock,
    FileObjectOffset => StubBytesFileStateLock,
    FramebufferInfoLock => FramebufferPresentationReceiverLock,
    FramebufferInfoLock => FramebufferViewBoundProtocolsLock,
    FramebufferInfoLock => FramebufferViewIdentityLock,
    FramebufferInfoLock => MemoryManagerStateLock,
    FsContextStateLock => MountsLevel,
    FsNodeAppend => MemoryManagerStateLock,
    FsNodeAppend => UninterruptibleLock,
    FsNodeFlockInfoLock => WaitQueueImplLock,
    FsNodeInfoLevel => FsNodeWriteGuardStateLock,
    FsNodeInfoRecursiveLevel => FsRename,
    FsNodeWriteGuardStateLock => FsNodeFsVerityLock,
    FsNodeWriteGuardStateLock => SeLinuxQueryCacheResetLock,
    FsNodeWriteGuardStateLock => ThreadGroupLimits,
    FsRename => DirEntryChildrenLevel,
    FsRenameRecursive => DirEntryChildrenRecursiveLevel,
    FunctionFsStateLock => MemoryManagerStateLock,
    FunctionFsStateLock => WaitQueueImplLock,
    FuseConnectionStateLock => PortWaiterCallbacksLock,
    FuseConnectionStateLock => WaitQueueImplLock,
    FuseDirEntryChildrenLevel => FuseFsNodeInfoLevel,
    FuseDirEntryChildrenLevel => FuseNodeStateLock,
    FuseFsNodeInfoLevel => UninterruptibleLock,
    FuseFsRenameLevel => FuseDirEntryChildrenLevel,
    FutexTableStateLock => FsContextStateLock,
    FutexTableStateLock => FsNodeInfoLevel,
    FutexTableStateLock => InflightVmsplicedPayloadsLock,
    FutexTableStateLock => MemoryManagerStateLock,
    GenericNetlinkServerStateLock => NetlinkSocketInnerLock,
    InotifyStateLock => EventHandlerReadyQueueLock,
    InotifyStateLock => MemoryManagerStateLock,
    InotifyStateLock => PortWaiterCallbacksLock,
    InotifyStateLock => WaitQueueImplLock,
    InputEventRelayOpenedFilesLock => WaitQueueImplLock,
    InputRelayDeviceInfosLock => InputDeviceInfoLock,
    IoUringStateLock => MemoryManagerStateLock,
    LoopDeviceStateLock => FsContextStateLock,
    LoopDeviceStateLock => FsNodeInfoLevel,
    LoopDeviceStateLock => RemoteBundleInnerLock,
    LoopDevicesLock => DeviceRegistryStateLevel,
    LoopDevicesLock => DynamicThreadSpawnerLock,
    LoopDevicesLock => LoopDeviceStateLock,
    LoopDevicesLock => SimpleDirectoryEntriesLock,
    LoopDevicesLock => TaskMutableStateLock,
    MagmaConnectionsLock => DirEntryChildrenLevel,
    MemoryAttributionPublisherLock => DynamicThreadSpawnerLock,
    MemoryDirectoryReaddirPositionLock => DirEntryChildrenLevel,
    MemoryManagerStateLock => ExpandoLock,
    MemoryManagerStateLock => FsContextStateLock,
    MemoryManagerStateLock => FsNodeInfoLevel,
    MemoryManagerStateLock => InflightVmsplicedPayloadsLock,
    MemoryManagerStateLock => MapInfoCacheBufLock,
    MemoryManagerStateLock => SeLinuxFsContextSidLock,
    MemoryManagerStateLock => SeLinuxQueryCacheResetLock,
    MemoryManagerStateLock => ThreadGroupLimits,
    MemoryManagerStateLock => UserFaultInner,
    MemoryPressureMonitor => MemoryPressureMonitorClientState,
    MemoryPressureMonitor => PortWaiterCallbacksLock,
    MountsLevel => MountSubmountsLock,
    NetlinkSocketInnerLock => EpollWaitableStateLock,
    NetlinkSocketInnerLock => EventHandlerReadyQueueLock,
    NetlinkSocketInnerLock => PortWaiterCallbacksLock,
    NetstackDevicesLock => SimpleDirectoryEntriesLock,
    NflogListenersLock => NetlinkSocketInnerLock,
    OverlayFsDirEntriesLock => MemoryManagerStateLock,
    OverlayFsStateLock => FsNodeInfoLevel,
    OverlayFsStateLock => SeLinuxQueryCacheResetLock,
    PidTableLock => CgroupPidTableLock,
    PidTableLock => MemoryAttributionPublisherLock,
    PidTableLock => ThreadGroupMutableStateLock,
    PidTableLock => ThreadGroupPtraceesLock,
    QbgReadQueueLock => MemoryManagerStateLock,
    RecordLocksStateLock => PortWaiterCallbacksLock,
    RecordLocksStateLock => WaitQueueImplLock,
    RemoteBinderHandleLevel => BinderProcsLevel,
    RemoteBlockDeviceRegistryDevicesLock => SimpleDirectoryEntriesLock,
    SeLinuxFsContextSidLock => SeLinuxQueryCacheResetLock,
    SeLinuxQueryCacheResetLock => SeLinuxSecurityServerStateLock,
    SignalFdMaskLock => ThreadGroupPendingSignalsLock,
    SimpleDirectoryEntriesLock => FsNodeInfoLevel,
    SimpleDirectoryEntriesLock => RwQueueInnerLock,
    SyslogSubscriptionLock => PortWaiterCallbacksLock,
    SyslogSubscriptionLock => WaitQueueImplLock,
    TaskCredsLock => DirEntryChildrenRecursiveLevel,
    TaskCredsLock => FsNodeInfoRecursiveLevel,
    TaskCredsLock => OverlayFsStateLock,
    TaskCredsLock => TaskFilesLock,
    TaskFilesLock => FdTableMutableStateLock,
    TaskMutableStateLock => EpollWaitableStateLock,
    TaskMutableStateLock => FutexTableStateLock,
    TaskMutableStateLock => IntervalTimerState,
    TaskMutableStateLock => PortWaiterCallbacksLock,
    TaskMutableStateLock => ProfileHandleCacheLock,
    TaskMutableStateLock => SeccompNotifierLock,
    TaskMutableStateLock => SignalActionsLock,
    TaskMutableStateLock => SignalFdMaskLock,
    TaskMutableStateLock => TaskCommandLevel,
    TaskMutableStateLock => TaskFilesLock,
    TaskMutableStateLock => ThreadGroupLimits,
    TaskMutableStateLock => UtsNamespaceLock,
    TerminalMutableStateLock => EventHandlerReadyQueueLock,
    TerminalMutableStateLock => TaskMutableStateLock,
    ThreadGroupLimits => SeLinuxQueryCacheResetLock,
    ThreadGroupMutableStateLock => DeviceTerminalsLock,
    ThreadGroupPtraceesLock => ThreadGroupMutableStateLock,
    TimerFileInfoLock => HrTimerManagerStateLock,
    TimerFileInfoLock => TaskMutableStateLock,
    TimerTableStateLock => HrTimerIsIntervalLock,
    TimerTableStateLock => IntervalTimerState,
    TracePerformanceEventManagerStateLock => PidToKoidMapInnerLock,
    UEventNetlinkSocketDeviceListenerKeyLock => DeviceRegistryStateLevel,
    UninterruptibleLock => AioPendingOperationsLock,
    UninterruptibleLock => AshmemStateLock,
    UninterruptibleLock => CgroupV1Level,
    UninterruptibleLock => ComponentMountRecordLock,
    UninterruptibleLock => CrashesPerProcessLock,
    UninterruptibleLock => DevKmsgLock,
    UninterruptibleLock => DeviceMapperRegistryDevicesLock,
    UninterruptibleLock => EbpfMapStateLevel,
    UninterruptibleLock => EbpfStateLock,
    UninterruptibleLock => ExecutorVmarManagerLock,
    UninterruptibleLock => FastrpcInnerState,
    UninterruptibleLock => FileEpollFilesLock,
    UninterruptibleLock => FramebufferInfoLock,
    UninterruptibleLock => FsNodeFlockInfoLock,
    UninterruptibleLock => FunctionFsStateLock,
    UninterruptibleLock => FuseConnectionStateLock,
    UninterruptibleLock => GenericNetlinkServerStateLock,
    UninterruptibleLock => InotifyWatchersLock,
    UninterruptibleLock => InputDeviceFileNodesLock,
    UninterruptibleLock => InputEventRelayOpenedFilesLock,
    UninterruptibleLock => IoUringStateLock,
    UninterruptibleLock => KernelIpTables,
    UninterruptibleLock => KernelSwapFiles,
    UninterruptibleLock => LoopDevicesLock,
    UninterruptibleLock => MagmaConnectionsLock,
    UninterruptibleLock => MemoryXattrStorageLevel,
    UninterruptibleLock => NflogListenersLock,
    UninterruptibleLock => OverlayFsStateLock,
    UninterruptibleLock => PerfEventLevel,
    UninterruptibleLock => PidTableLock,
    UninterruptibleLock => QbgReadQueueLock,
    UninterruptibleLock => QipcrtrSocketInnerLock,
    UninterruptibleLock => RecordLocksStateLock,
    UninterruptibleLock => RemoteBinderHandleLevel,
    UninterruptibleLock => RemoteBlockDeviceRegistryDevicesLock,
    UninterruptibleLock => SeLinuxFsContextSidLock,
    UninterruptibleLock => SeLinuxQueryCacheResetLock,
    UninterruptibleLock => SyslogSubscriptionLock,
    UninterruptibleLock => TaskCredsLock,
    UninterruptibleLock => TracePerformanceEventManagerStateLock,
    UninterruptibleLock => UinputDeviceStateLock,
    UninterruptibleLock => UserFaultInner,
    UninterruptibleLock => VsockSocketInnerLock,
    UnixSocketInnerLock => EpollWaitableStateLock,
    UnixSocketInnerLock => EventHandlerReadyQueueLock,
    UnixSocketInnerLock => MemoryManagerStateLock,
    UnixSocketInnerLock => PortWaiterCallbacksLock,
    UnixSocketInnerLock => SeLinuxPeerSidLock,
    UnixSocketInnerLock => SeLinuxQueryCacheResetLock,
    UnixSocketInnerLock => SocketStateLock,
    Unlocked => FileObjectOffset,
    Unlocked => FuseFsRenameLevel,
    Unlocked => UninterruptibleLock,
    VsockSocketInnerLock => PortWaiterCallbacksLock,
    VsockSocketInnerLock => WaitQueueImplLock,
    WaitQueueImplLock => PortWaiterWaitQueuesLock,
    WaitQueueImplLock => SeLinuxQueryCacheResetLock,
    WaiterEventHandlerLock => EpollWaitableStateLock,
    // keep-sorted end

    // Terminal Levels. No lock level should ever be defined after this.
    // Can be used for any locks that is never acquired before any other lock.
    // keep-sorted start
    Terminal(AioEventsLock),
    Terminal(AuditDenyCountsLock),
    Terminal(AuditNetlinkClientAuditResponseLock),
    Terminal(AuditQueueLock),
    Terminal(AuditSinkLock),
    Terminal(BinderThreadRequeueEventLock),
    Terminal(BootedLock),
    Terminal(CgroupDirectoryNodesLock),
    Terminal(ComponentControllerLock),
    Terminal(CoreDumpListLock),
    Terminal(CpuFreqProxyCacheLock),
    Terminal(DynamicThreadSpawnerLock),
    Terminal(EbpfVerifierDependenciesLock),
    Terminal(EventFdInnerLock),
    Terminal(EventHandlerReadyQueueLock),
    Terminal(ExpandoLock),
    Terminal(FileAsyncOwnerLock),
    Terminal(FileLeaseLock),
    Terminal(FileServerStatsLock),
    Terminal(FileSystemEntriesLock),
    Terminal(FileSystemPermanentLock),
    Terminal(FramebufferMemoryLock),
    Terminal(FramebufferPresentationReceiverLock),
    Terminal(FramebufferSceneStateLock),
    Terminal(FramebufferViewBoundProtocolsLock),
    Terminal(FramebufferViewIdentityLock),
    Terminal(FsNodeFsVerityLock),
    Terminal(FsRegistryLock),
    Terminal(FuchsiaRemoteTargetLock),
    Terminal(FunctionFsResultLock),
    Terminal(FuseConnectionsLock),
    Terminal(FuseNodeStateLock),
    Terminal(HrTimerIsIntervalLock),
    Terminal(HrTimerManagerStateLock),
    Terminal(IcmpPingGidsLock),
    Terminal(InotifyWatchersLock),
    Terminal(InputDeviceInfoLock),
    Terminal(InputFileInputFileLock),
    Terminal(InputRelayDisplaySizeLock),
    Terminal(KgslAllocatorLock),
    Terminal(KgslContextsLock),
    Terminal(KgslGpuObjsLock),
    Terminal(KgslSyncSourcesLock),
    Terminal(MagmaBuffersLock),
    Terminal(MagmaDevicesLock),
    Terminal(MagmaSemaphoresLock),
    Terminal(MapInfoCacheBufLock),
    Terminal(MemoryManagerCachedStatsLock),
    Terminal(MountSubmountsLock),
    Terminal(NamespaceFlagsLock),
    Terminal(NanohubContentsLock),
    Terminal(NanohubServiceLock),
    Terminal(NetnsIdLock),
    Terminal(NmfsNetworkManagerLock),
    Terminal(NotFoundCountsLock),
    Terminal(OdpmRailLastReadingLock),
    Terminal(OdpmRailProxyLock),
    Terminal(PagerFilesByInodeLock),
    Terminal(PagerFilesystemsLock),
    Terminal(PerfFormatIdLookupTableLock),
    Terminal(PerfRingBufferStateLock),
    Terminal(PidToKoidMapInnerLock),
    Terminal(PortWaiterCallbacksLock),
    Terminal(PortWaiterWaitQueuesLock),
    Terminal(PowerMessageCountersLock),
    Terminal(ProfileHandleCacheLock),
    Terminal(PtsIdsSetLock),
    Terminal(QbgShutdownLock),
    Terminal(RcuCacheLock),
    Terminal(ReadWriteBytesFileLock),
    Terminal(RebootErrorStateLock),
    Terminal(RemoteBinderControllerLock),
    Terminal(RemoteBinderResponderLock),
    Terminal(RemoteBundleInnerLock),
    Terminal(RemoteUnixDomainSocketStateLock),
    Terminal(RwQueueInnerLock),
    Terminal(SeLinuxPeerSidLock),
    Terminal(SeLinuxPendingEntriesLock),
    Terminal(SeLinuxPendingFileSystemsLock),
    Terminal(SeLinuxSecurityServerStateLock),
    Terminal(SeLinuxUpdateLock),
    Terminal(SignalActionsLock),
    Terminal(SocketStateLock),
    Terminal(StubBytesFileStateLock),
    Terminal(SuspendResumeManagerInnerLock),
    Terminal(SyscallLogFiltersLock),
    Terminal(SyslogStateLock),
    Terminal(TaskCommandLevel),
    Terminal(ThermalChargeLevelLock),
    Terminal(ThreadLockupDetectorRegistryLock),
    Terminal(ThrottledCoreDumpsLock),
    Terminal(TouchPowerPolicyEnabledLock),
    Terminal(TraceFsDataLock),
    Terminal(TunDevTunLock),
    Terminal(UinputDeviceStateLock),
    Terminal(UtsNamespaceLock),
    Terminal(VmspliceSegmentsLock),
    Terminal(WakeSourcesLock),
    Terminal(WakeWatchersLock),
    // keep-sorted end
}
