# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "mock-health-verification",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    test_deps = [
        "//src/lib/fuchsia",
    ],
    visibility = [
        "//src/sys/pkg/bin/system-update-committer:__pkg__",
        "//src/sys/pkg/tests/omaha-client:__pkg__",
        "//src/sys/pkg/tests/pkg-cache:__pkg__",
        "//src/sys/pkg/tests/system-update-checker:__pkg__",
        "//src/sys/pkg/tests/system-update-committer:__pkg__",
        "//vendor/google:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/fidl/rust/fidl",
        "//src/lib/fuchsia-async",
        "//src/sys/pkg/fidl/fuchsia.update.verify:fuchsia.update.verify_rust",
        "//third_party/rust_crates/vendor:futures",
    ],
)
