# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_host) {
  # NOTE: This redirection group is necessary because static check builders
  # reference this label directly. It'll be removed when builder configs are
  # updated.
  group("host") {
    deps =
        [ "//build/bazel/host:bazel_root_host_tools.check-licenses.host_tool" ]
  }
}
