# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "depfile",
    srcs = [
        "src/depfile.rs",
        "src/lib.rs",
    ],
    edition = "2024",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    test_deps = ["//third_party/rust_crates/vendor:tempfile"],
    visibility = [
        "//build/assembly/tools/assembly_config:__pkg__",
        "//src/lib/assembly/container:__pkg__",
        # //src/lib:tests depends on :depfile_test.
        "//src/lib:__pkg__",
        "//src/starnix/lib/starnix_container:__pkg__",
        "//src/starnix/tools/gen_android_starnix_container:__pkg__",
        "//vendor/google:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:camino",
    ],
)
