# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load("//build/bazel/rules/packages:fx_package.bzl", "fx_package")
load("//build/bazel/rules/packages:fx_packaged_binary.bzl", "fx_packaged_binary")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")
load("//build/bazel/rules/testing:fx_test.bzl", "fx_test")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "profile-client",
    srcs = [
        "src/error.rs",
        "src/lib.rs",
    ],
    edition = "2024",
    rustc_flags = ["-Dunused_results"],
    # @bazel2gn:skip
    test_deps = [
        "//src/connectivity/bluetooth/testing/bt-channel-test-support",
        "//src/lib/fuchsia",
        "//src/lib/fuchsia-async",
        "//third_party/rust_crates/vendor:futures-test",
        "//third_party/rust_crates/vendor:test-case",
    ],
    visibility = [
        "//src/connectivity/bluetooth:__subpackages__",
        "//vendor/google:__subpackages__",
    ],
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.bluetooth.bredr:fuchsia.bluetooth.bredr_rust",
        "//sdk/fidl/fuchsia.bluetooth:fuchsia.bluetooth_rust",
        "//src/connectivity/bluetooth/lib/fuchsia-bluetooth",
        "//src/lib/fidl/rust/fidl",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:log",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)

rustc_library(
    name = "test-profile-server",
    testonly = True,
    srcs = ["src/test/lib.rs"],
    crate_root = "src/test/lib.rs",
    edition = "2024",
    rustc_flags = ["-Dunused_results"],
    visibility = [
        "//src/connectivity/bluetooth/lib/bt-hfp:__pkg__",
        "//src/connectivity/bluetooth/profiles/bt-hfp-hands-free:__pkg__",
        "//src/connectivity/bluetooth/profiles/bt-hid:__pkg__",
    ],
    deps = [
        ":profile-client",
        "//sdk/fidl/fuchsia.bluetooth.bredr:fuchsia.bluetooth.bredr_rust",
        "//sdk/fidl/fuchsia.bluetooth:fuchsia.bluetooth_rust",
        "//src/connectivity/bluetooth/lib/fuchsia-bluetooth",
        "//src/lib/fidl/rust/fidl",
        "//third_party/rust_crates/vendor:futures",
    ],
)

# @bazel2gn:skip
fx_packaged_binary(
    name = "profile-client_test_packaged_bin",
    testonly = True,
    binary = ":profile-client_test",
    binary_name = "profile_client_lib_test",
)

# @bazel2gn:skip
fx_component_manifest(
    name = "profile-client-tests-manifest",
    testonly = True,
    component_name = "profile-client-tests",
    includes = [
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/rust:default.shard.cml",
    ],
    manifest = "meta/profile_client_tests.cml",
)

# @bazel2gn:skip
fx_test_component(
    name = "profile-client-tests-component",
    compiled_manifest = ":profile-client-tests-manifest",
    component_name = "profile-client-tests",
    deps = [":profile-client_test_packaged_bin"],
)

# @bazel2gn:skip
fx_package(
    name = "profile-client-tests-package",
    package_name = "profile-client-tests",
    test_components = [":profile-client-tests-component"],
)

# @bazel2gn:skip
fx_test(
    name = "profile-client-tests",
    package = ":profile-client-tests-package",
)
