# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load("//build/bazel/rules/packages:fx_package.bzl", "fx_package")
load("//build/bazel/rules/packages:fx_packaged_binary.bzl", "fx_packaged_binary")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")
load("//build/bazel/rules/testing:fx_test.bzl", "fx_test")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fuchsia-rseq",
    srcs = ["src/lib.rs"],
    edition = "2024",
    visibility = ["//src/lib/fuchsia-rcu:__pkg__"],
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//sdk/rust/zx-types",
        "//src/lib/fuchsia-runtime",
        "//src/lib/fuchsia-sync",
    ],
)

# @bazel2gn:skip
fx_packaged_binary(
    name = "fuchsia-rseq_test_packaged_bin",
    testonly = True,
    binary = ":fuchsia-rseq_test",
    binary_name = "fuchsia_rseq_lib_test",
)

# @bazel2gn:skip
fx_component_manifest(
    name = "fuchsia-rseq-tests-manifest",
    testonly = True,
    component_name = "fuchsia-rseq-tests",
    includes = [
        "//sdk/lib/sys/component:realm_builder.shard.cml",
        "//sdk/lib/sys/component:realm_builder_base_no_diagnostics.shard.cml",
        "//sdk/lib/sys/component:realm_builder_no_diagnostics.shard.cml",
        "//sdk/lib/syslog:client.shard.cml",
        "//sdk/lib/syslog:offer.shard.cml",
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/rust:next-vdso.shard.cml",
    ],
    manifest = "meta/fuchsia_rseq_tests.cml",
)

# @bazel2gn:skip
fx_test_component(
    name = "fuchsia-rseq-tests-component",
    compiled_manifest = ":fuchsia-rseq-tests-manifest",
    component_name = "fuchsia-rseq-tests",
    deps = [":fuchsia-rseq_test_packaged_bin"],
)

# @bazel2gn:skip
fx_package(
    name = "fuchsia-rseq-tests-package",
    package_name = "fuchsia-rseq-tests",
    test_components = [":fuchsia-rseq-tests-component"],
)

# @bazel2gn:skip
fx_test(
    name = "fuchsia-rseq-tests",
    max_log_severity = "ERROR",
    package = ":fuchsia-rseq-tests-package",
)
