// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use assembly_container::WalkPaths;
use camino::Utf8PathBuf;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Platform configuration options for the starnix area.
#[derive(Debug, Deserialize, Serialize, PartialEq, JsonSchema, WalkPaths)]
#[serde(default, deny_unknown_fields)]
pub struct PowerConfig {
    /// Whether power suspend/resume is supported.
    #[serde(skip_serializing_if = "crate::common::is_default")]
    pub suspend_enabled: bool,

    /// Whether power management for the GPU subsystem is enabled.
    /// Defaults to 'true'.
    #[serde(skip_serializing_if = "bool::clone")]
    pub gpu_power_management_enabled: bool,

    /// Deprecated and ignored. Storage power management is enabled by the
    /// `fuchsia::storage_power_management` and `fuchsia::suspending_token`
    /// board features instead.
    ///
    /// This is still accepted so that product configs generated by older
    /// versions of assembly (e.g. hybrid product configs) continue to parse,
    /// but it is never serialized.
    /// TODO(https://fxbug.dev/419601965): Remove once no product configs
    /// contain this field.
    #[serde(skip_serializing)]
    pub storage_power_management_enabled: Option<bool>,

    /// Whether to include the power framework components that are needed
    /// for power system non-hermetic testing in the platform.
    #[serde(skip_serializing_if = "crate::common::is_default")]
    pub enable_non_hermetic_testing: bool,

    /// Configuration of devices and drivers for power-metrics collection
    #[schemars(schema_with = "crate::option_path_schema")]
    #[walk_paths]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics_logging_config: Option<Utf8PathBuf>,
}

impl Default for PowerConfig {
    fn default() -> Self {
        Self {
            suspend_enabled: false,
            gpu_power_management_enabled: true,
            storage_power_management_enabled: None,
            enable_non_hermetic_testing: false,
            metrics_logging_config: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_serialization() {
        crate::common::tests::default_serialization_helper::<PowerConfig>();
    }

    #[test]
    fn test_deprecated_storage_power_management_enabled_is_not_serialized() {
        let config: PowerConfig = serde_json::from_value(serde_json::json!({
            "suspend_enabled": true,
            "storage_power_management_enabled": true,
        }))
        .unwrap();
        assert_eq!(
            serde_json::to_value(&config).unwrap(),
            serde_json::json!({ "suspend_enabled": true })
        );
    }

    #[test]
    fn test_gpu_power_management_enabled_default_and_override() {
        let default_config: PowerConfig = serde_json::from_value(serde_json::json!({})).unwrap();
        assert!(default_config.gpu_power_management_enabled);

        let disabled_config: PowerConfig = serde_json::from_value(serde_json::json!({
            "gpu_power_management_enabled": false,
        }))
        .unwrap();
        assert!(!disabled_config.gpu_power_management_enabled);
        assert_eq!(
            serde_json::to_value(&disabled_config).unwrap(),
            serde_json::json!({ "gpu_power_management_enabled": false })
        );
    }
}
