# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "gopkg",
    srcs = [
        "model.go",
        "report.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/sdk/ctf/plasa/model",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:gopkg.in/yaml.v2",
    ],
)
