# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

if (is_host) {
  bazel_host_tool("netruncmd") {
    bazel_target = ":netruncmd"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/netruncmd"
    install_host_tool = true
  }

  bazel_host_tool("netcp") {
    bazel_target = ":netcp"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/netcp"
    install_host_tool = true
  }

  bazel_host_tool("netls") {
    bazel_target = ":netls"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/netls"
    install_host_tool = true
  }

  bazel_host_tool("netaddr") {
    bazel_target = ":netaddr"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/netaddr"
    install_host_tool = true
  }
}

group("netprotocol") {
  deps = [
    ":netaddr($host_toolchain)",
    ":netcp($host_toolchain)",
    ":netls($host_toolchain)",
    ":netruncmd($host_toolchain)",
  ]
}
