# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "@fuchsia_rules_common//packages:resources.bzl",
    "fuchsia_package_resource_group",
)
load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component_manifest",
    "fx_test_component",
)
load("//build/bazel/rules/packages:fx_package.bzl", "fx_package")
load("//build/bazel/rules/packages:fx_packaged_binary.bzl", "fx_packaged_binary")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")
load("//build/bazel/rules/testing:fx_test.bzl", "fx_test")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "objects",
    srcs = [
        "src/error.rs",
        "src/folder_listing.rs",
        "src/lib.rs",
    ],
    edition = "2024",
    rustc_flags = ["-Dunused_results"],
    # @bazel2gn:skip
    test_deps = [
        "//sdk/lib/fdio",
        "//src/lib/fuchsia",
    ],
    visibility = [
        "//src/connectivity/bluetooth/lib/bt-map:__pkg__",
        "//src/connectivity/bluetooth/lib/bt-obex:__pkg__",
        "//src/connectivity/bluetooth/profiles/bt-map-mce:__pkg__",
    ],
    # @bazel2gn:skip
    with_unit_tests = True,
    deps = [
        "//third_party/rust_crates/vendor:bitflags",
        "//third_party/rust_crates/vendor:chrono",
        "//third_party/rust_crates/vendor:thiserror",
        "//third_party/rust_crates/vendor:xml",
    ],
)

# @bazel2gn:skip
fuchsia_package_resource_group(
    name = "objects-test-files",
    testonly = True,
    srcs = [
        "test/bad_sample.xml",
        "test/bad_sample_folder_listing_1.xml",
        "test/bad_sample_folder_listing_2.xml",
        "test/bad_sample_folder_listing_3.xml",
        "test/bad_sample_folder_listing_4.xml",
        "test/bad_sample_folder_listing_5.xml",
        "test/bad_sample_folder_listing_6.xml",
        "test/bad_sample_folder_listing_7.xml",
        "test/bad_sample_folder_listing_8.xml",
        "test/sample_folder_listing_1.xml",
        "test/sample_folder_listing_2.xml",
        "test/sample_folder_listing_3.xml",
    ],
    basename_only = True,
    dest = "data",
)

# @bazel2gn:skip
fx_packaged_binary(
    name = "objects_test_packaged_bin",
    testonly = True,
    binary = ":objects_test",
    binary_name = "objects_lib_test",
)

# @bazel2gn:skip
fx_component_manifest(
    name = "bt-obex-objects-tests-manifest",
    testonly = True,
    component_name = "bt-obex-objects-tests",
    includes = [
        "//sdk/lib/syslog:use.shard.cml",
        "//src/sys/test_runners/rust:default.shard.cml",
    ],
    manifest = "meta/bt_obex_objects_tests.cml",
)

# @bazel2gn:skip
fx_test_component(
    name = "bt-obex-objects-tests-component",
    compiled_manifest = ":bt-obex-objects-tests-manifest",
    component_name = "bt-obex-objects-tests",
    deps = [
        ":objects-test-files",
        ":objects_test_packaged_bin",
    ],
)

# @bazel2gn:skip
fx_package(
    name = "bt-obex-objects-tests-package",
    package_name = "bt-obex-objects-tests",
    test_components = [":bt-obex-objects-tests-component"],
)

# @bazel2gn:skip
fx_test(
    name = "bt-obex-objects-tests",
    package = ":bt-obex-objects-tests-package",
    visibility = ["//src/connectivity/bluetooth/lib/bt-obex:__pkg__"],
)
