# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "tool",
    srcs = [
        "src/lib.rs",
        "src/platform.rs",
        "src/serde_arc.rs",
        "src/testing.rs",
        "src/tool.rs",
    ],
    crate_name = "assembly_tool",
    edition = "2024",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    visibility = [
        "//build/assembly/tools/assembly:__pkg__",
        "//src/developer/ffx/plugins:__subpackages__",
        "//src/lib/assembly:__subpackages__",
    ],
    with_host_unit_tests = True,
    deps = [
        "//src/lib/assembly/util",
        "//src/lib/utf8_path",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:camino",
        "//third_party/rust_crates/vendor:dyn-clone",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:serde_json",
    ],
)
